// CHANNEL PLAN — konu kumeleri + ic baglanti (session growth) plani.
//
// Tek videonun izlenmesi degil, bir izleyicinin BIRDEN FAZLA video izlemesi
// hedeflenir. Her video icin: onceki/sonraki ilgili video, playlist, end screen
// videosu, sabit yorumda anilacak video, aciklamada anilacak video.
//
// Ayni kumedeki videolar bilerek birbirini onerir. Kume playlist'i ancak
// kumede yeterli YAYINLANMIS video olunca (config clusters.minVideosForPlaylist)
// acilir — tek videolu bos listeler kanali zayif gosterir.
//
// Kullanim: node channel-plan.js   ->  channel/topic-clusters.json + channel/internal-linking-plan.md
"use strict";
const path = require("path");
const { KOK, jsonOku, jsonYaz, metinYaz } = require("./lib/ortak");
const { ayar } = require("./lib/ayar");
const K = require("./lib/kutuphane");

const PLAYLISTLER = path.join(KOK, "icerik", "playlistler.json");
const url = (id) => id ? "https://youtu.be/" + id : null;

function kur() {
  const konular = K.konular();
  const yay = K.yayinlananlar();
  const pl = jsonOku(PLAYLISTLER, {});
  const minPl = ayar().clusters.minVideosForPlaylist;
  const kumeler = {};
  for (const [id, k] of Object.entries(K.KUMELER)) kumeler[id] = { id, ad: k.ad, aciklama: k.aciklama, videolar: [] };
  for (const k of konular) {
    const id = K.kumeBul(k);
    const y = yay.filter((x) => x.slug === k.slug).pop();
    const titles = jsonOku(K.paketYolu(k.slug, "titles.json"), null);
    kumeler[id].videolar.push({ slug: k.slug, baslik: (y && y.baslik) || (titles && titles.secilen) || k.baslik,
      format: K.formatBul(k), durum: y ? "published" : "queued", videoId: y ? y.videoId : null, tarih: y ? y.tarih : null });
  }
  for (const c of Object.values(kumeler)) {
    // yayinlananlar tarih sirasi, sonra kuyruk (alfabetik = uretim sirasi)
    c.videolar.sort((a, b) => (a.tarih && b.tarih ? a.tarih.localeCompare(b.tarih) : a.tarih ? -1 : b.tarih ? 1 : a.slug.localeCompare(b.slug)));
    const yayinSay = c.videolar.filter((v) => v.durum === "published").length;
    c.playlist = { ad: c.ad, id: pl[c.ad] || null, durum: yayinSay >= minPl ? "active" : `waiting (${yayinSay}/${minPl} published)` };
  }
  return { olusturuldu: new Date().toISOString(), kurallar: { minVideosForPlaylist: minPl },
    kumeler: Object.values(kumeler).filter((c) => c.videolar.length) };
}

// Bir video icin baglanti plani
function baglanti(plan, slug) {
  const c = plan.kumeler.find((x) => x.videolar.some((v) => v.slug === slug));
  if (!c) return null;
  const l = c.videolar, i = l.findIndex((v) => v.slug === slug);
  const yay = (v) => v && v.durum === "published";
  const onceki = [...l.slice(0, i)].reverse().find(yay) || null;
  const sonraki = l.slice(i + 1).find(yay) || null;
  // Kumede yayinli baska video yoksa kanalin EN COK izlenen videosunu oner (son analiz
  // verisinden; veri yoksa en yenisi) — izleyici kanalda kalsin.
  const izlenme = (v) => ((jsonOku(path.join(KOK, "analysis", v.videoId || "_", "data.json"), null) || {}).metrikler || {}).views;
  const kanaldan = plan.kumeler.flatMap((x) => x.videolar).filter((v) => yay(v) && v.slug !== slug)
    .sort((a, b) => ((izlenme(b) || {}).deger || 0) - ((izlenme(a) || {}).deger || 0) || String(b.tarih).localeCompare(String(a.tarih)));
  const enIyi = onceki || sonraki || kanaldan[0] || null;
  const uzun = l.find((v) => yay(v) && v.format === "long" && v.slug !== slug) || null;
  return {
    kume: c.ad, kumeId: c.id,
    onceki: onceki && { slug: onceki.slug, baslik: onceki.baslik, url: url(onceki.videoId) },
    sonraki: sonraki && { slug: sonraki.slug, baslik: sonraki.baslik, url: url(sonraki.videoId) },
    sonrakiKuyruk: (l.slice(i + 1).find((v) => v.durum === "queued") || {}).baslik || null,
    playlist: c.playlist,
    endScreen: (uzun || enIyi) && { slug: (uzun || enIyi).slug, baslik: (uzun || enIyi).baslik, url: url((uzun || enIyi).videoId),
      not: "Shorts have no end screens — set this as the Short's 'Related video' in Studio. Long-form: end-screen element." },
    sabitYorumVideo: enIyi && { slug: enIyi.slug, baslik: enIyi.baslik, url: url(enIyi.videoId) },
    aciklamaVideo: enIyi && { slug: enIyi.slug, baslik: enIyi.baslik, url: url(enIyi.videoId) },
  };
}

function rapor(plan) {
  const s = ["# Internal linking plan", "",
    "Generated by `node channel-plan.js`. Every video points viewers to the next relevant Failure Reconstructed episode.",
    "YouTube's API cannot set end screens, Shorts 'Related video' links or pin comments — those rows are **manual Studio actions** (1 click each).", ""];
  for (const c of plan.kumeler) {
    s.push(`## ${c.ad}`, "", `_${c.aciklama}_`, "", `Playlist: **${c.playlist.ad}** — ${c.playlist.durum}${c.playlist.id ? " (https://www.youtube.com/playlist?list=" + c.playlist.id + ")" : ""}`, "");
    s.push("| Video | Status | Previous | Next | End screen / Related video | Description link |", "|---|---|---|---|---|---|");
    for (const v of c.videolar) {
      const b = baglanti(plan, v.slug);
      const f = (x) => x ? (x.url ? `[${x.baslik}](${x.url})` : x.baslik) : "—";
      s.push(`| ${v.baslik}${v.videoId ? ` ([${v.videoId}](https://youtu.be/${v.videoId}))` : ""} | ${v.durum} | ${f(b.onceki)} | ${f(b.sonraki) !== "—" ? f(b.sonraki) : (b.sonrakiKuyruk ? "_queued: " + b.sonrakiKuyruk + "_" : "—")} | ${f(b.endScreen)} | ${f(b.aciklamaVideo)} |`);
    }
    s.push("");
  }
  return s.join("\n");
}

function calistir() {
  const plan = kur();
  jsonYaz(path.join(KOK, "channel", "topic-clusters.json"), plan);
  metinYaz(path.join(KOK, "channel", "internal-linking-plan.md"), rapor(plan));
  return plan;
}

module.exports = { kur, baglanti, calistir, PLAYLISTLER };

if (require.main === module) {
  const p = calistir();
  for (const c of p.kumeler) console.log(`${c.ad.padEnd(34)} ${String(c.videolar.length).padStart(2)} video  playlist: ${c.playlist.durum}`);
}
